- name: apt-get update
  apt: update_cache=yes

- name: find out if https exists in apt methods
  stat: path=/usr/lib/apt/methods/https
  register: existence

- name: install apt-transport-https if https not in methods
  apt: name=apt-transport-https
       state=present
  when: not existence.stat.exists

- name: add docker repository key
  shell: apt-key adv --keyserver {{ docker_apt_key_server }} --recv-keys {{ docker_apt_key }}

- name: add a docker.list file to apt source list
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list
        mode=0644

- name: update again
  apt: update_cache=yes

- name: get docker and brctl
  apt: name={{ item }}
       state=installed
  with_items:
    - lxc-docker
    - bridge-utils
