- name: chef-server cleanse
  shell: chef-server-ctl cleanse

- name: create chef-server directory
  file: path=/etc/chef-server state=directory

- name: copy chef-server.rb
  copy: src=chef-server.rb dest=/etc/chef-server/chef-server.rb mode=644 backup=yes

- name: reconfigure chef-server
  shell: chef-server-ctl reconfigure

- name: test chef-server
  shell: chef-server-ctl test
