---

- name: install git
  apt: name=git
       state=installed
       update_cache=yes

- name: fact of chef-server
  shell: dpkg -l
  register: packages

# get precise chef-server deb pkg if ubuntu is 12.04
- name: get chef-server
  get_url: url={{ chef_server_precise }}
           dest=/tmp/chef-server.deb
  when: "'chef-server' not in packages.stdout and ansible_distribution_major_version == '12'"

- name: install chef-server
  apt: deb=/tmp/chef-server.deb
       state=installed

- name: get chef-client
  get_url: url={{ chef_client_precise }}
           dest=/tmp/chef-client.rpm
  when: "'chef' not in packages.stdout and ansbile_distribution_major_version == '12'"

- name: install chef-client
  apt: deb=/tmp/chef-client.deb
       state=installed
  when: "'chef' not in packages.stdout"
